/**
 * Этапы и переходы по регламенту «Структура · Продажи» + Miro.
 * Порядок nodes = порядок колонок слева направо (один «хребет»).
 * Типы связей: main — основной ход, move — товар/перемещение,
 * back — возврат назад, ok — в Успех, fail — в Провал.
 */

const BOARDS = {
  offline: {
    tab: "Оффлайн",
    zones: [
      { title: "Квалификация", from: "new", to: "want" },
      { title: "Перемещение товара", from: "wait", to: "hold" },
      { title: "Встреча", from: "meet", to: "meet" },
      { title: "Аренда", from: "rentpaid", to: "renting" },
      { title: "Сертификат", from: "cert", to: "cert" },
      { title: "Итог · сбор ОС", from: "success", to: "success", tall: true },
    ],
    nodes: [
      ["new", "Новая заявка", "start"],
      ["work", "Взято в работу", "stage"],
      ["promise", "Дано обещание", "stage"],
      ["want", "Хочет прийти", "stage"],
      ["wait", "Ждет товар", "move"],
      ["transit", "Товар в пути", "move"],
      ["instore", "Товар в магазине", "move"],
      ["hold", "Товар отложен", "move"],
      ["meet", "Встреча назначена", "meet"],
      ["rentpaid", "Аренда оплачена", "rent"],
      ["renting", "В аренде", "rent"],
      ["cert", "Сертификат оплачен", "cert"],
      ["success", "Успех", "success"],
    ],
    edges: [
      ["new", "work", "main"],
      ["work", "promise", "main"],
      ["work", "want", "main"],
      ["work", "wait", "move"],
      ["work", "meet", "main"],
      ["work", "cert", "main"],
      ["promise", "want", "main"],
      ["promise", "wait", "move"],
      ["promise", "meet", "main"],
      ["want", "wait", "move"],
      ["want", "meet", "main"],
      ["wait", "transit", "move"],
      ["transit", "instore", "move"],
      ["instore", "hold", "move"],
      ["hold", "meet", "main"],
      ["meet", "rentpaid", "main"],
      ["meet", "cert", "main"],
      ["meet", "success", "ok"],
      ["rentpaid", "renting", "main"],
      ["renting", "success", "ok"],
      ["cert", "success", "ok"],
      ["work", "fail", "fail"],
      ["promise", "fail", "fail"],
      ["want", "fail", "fail"],
      ["wait", "fail", "fail"],
      ["transit", "fail", "fail"],
      ["instore", "fail", "fail"],
      ["hold", "fail", "fail"],
      ["meet", "fail", "fail"],
      ["rentpaid", "fail", "fail"],
      ["renting", "fail", "fail"],
      ["cert", "fail", "fail"],
    ],
  },

  online: {
    tab: "Онлайн",
    zones: [
      { title: "Квалификация", from: "new", to: "want" },
      { title: "Перемещение товара", from: "wait", to: "hold" },
      { title: "Сборка заказа", from: "assemble", to: "courier" },
      { title: "Доставка", from: "sent", to: "delivered" },
      { title: "Отработка возражений", from: "notbought", to: "notbought" },
      { title: "Сертификат", from: "cert", to: "cert" },
      { title: "Итог · сбор ОС", from: "success", to: "success", tall: true },
    ],
    nodes: [
      ["new", "Новая заявка", "start"],
      ["work", "Взято в работу", "stage"],
      ["promise", "Дано обещание", "stage"],
      ["want", "Хочет заказать", "stage"],
      ["wait", "Ждет товар", "move"],
      ["transit", "Товар в пути", "move"],
      ["instore", "Товар в магазине", "move"],
      ["hold", "Товар отложен", "move"],
      ["assemble", "Передан на сборку", "meet"],
      ["packed", "Собран", "meet"],
      ["courier", "Вызван курьер", "meet"],
      ["sent", "Отправлен", "stage"],
      ["delivered", "Доставлен", "stage"],
      ["notbought", "Не выкуплен", "objection"],
      ["cert", "Сертификат оплачен", "cert"],
      ["success", "Успех", "success"],
    ],
    edges: [
      ["new", "work", "main"],
      ["work", "promise", "main"],
      ["work", "want", "main"],
      ["work", "wait", "move"],
      ["work", "assemble", "main"],
      ["work", "cert", "main"],
      ["promise", "want", "main"],
      ["promise", "wait", "move"],
      ["promise", "assemble", "main"],
      ["want", "wait", "move"],
      ["want", "assemble", "main"],
      ["wait", "transit", "move"],
      ["transit", "instore", "move"],
      ["instore", "hold", "move"],
      ["hold", "assemble", "main"],
      ["assemble", "packed", "main"],
      ["packed", "courier", "main"],
      ["courier", "sent", "main"],
      ["sent", "delivered", "main"],
      ["sent", "notbought", "move"],
      ["delivered", "success", "ok"],
      ["delivered", "notbought", "move"],
      ["notbought", "assemble", "back"],
      ["notbought", "promise", "back"],
      ["notbought", "wait", "back"],
      ["cert", "success", "ok"],
      ["work", "fail", "fail"],
      ["promise", "fail", "fail"],
      ["want", "fail", "fail"],
      ["wait", "fail", "fail"],
      ["transit", "fail", "fail"],
      ["instore", "fail", "fail"],
      ["hold", "fail", "fail"],
      ["assemble", "fail", "fail"],
      ["packed", "fail", "fail"],
      ["courier", "fail", "fail"],
      ["notbought", "fail", "fail"],
      ["cert", "fail", "fail"],
    ],
  },

  complaints: {
    tab: "Жалобы",
    zones: [
      { title: "Квалификация", from: "work", to: "want" },
      { title: "Перемещение товара", from: "move", to: "hold" },
      { title: "Встреча", from: "meet", to: "meet" },
      { title: "Итог · сбор ОС", from: "success", to: "success", tall: true },
    ],
    nodes: [
      ["work", "Взято в работу", "start"],
      ["agree", "Определены договоренности", "stage"],
      ["want", "Хочет прийти", "stage"],
      ["move", "Запрошено перемещение товара", "move"],
      ["instore", "Товар в магазине", "move"],
      ["hold", "Товар отложен", "move"],
      ["meet", "Встреча назначена", "meet"],
      ["success", "Успех", "success"],
    ],
    edges: [
      ["work", "agree", "main"],
      ["work", "want", "main"],
      ["work", "move", "move"],
      ["work", "meet", "main"],
      ["agree", "want", "main"],
      ["agree", "move", "move"],
      ["agree", "meet", "main"],
      ["want", "move", "move"],
      ["want", "meet", "main"],
      ["move", "instore", "move"],
      ["instore", "hold", "move"],
      ["hold", "meet", "main"],
      ["hold", "want", "back"],
      ["meet", "want", "back"],
      ["meet", "success", "ok"],
      ["work", "fail", "fail"],
      ["agree", "fail", "fail"],
      ["want", "fail", "fail"],
      ["move", "fail", "fail"],
      ["instore", "fail", "fail"],
      ["hold", "fail", "fail"],
      ["meet", "fail", "fail"],
    ],
  },
};
